### ISSUE TITLE
InvalidByte on string containing unicodes

### ISSUE THREAD

**Issue by soywod** [TornaxO7/rfc2047-decoder#19]
Some base 64 strings are not decoded properly: https://github.com/marshallpierce/rust-base64/issues/194.

**Comment by TornaxO7** [comment]
I think that this can be closed since we received an answer from them: <https://github.com/marshallpierce/rust-base64/issues/194#issuecomment-1276224130> What do you think?

**Comment by soywod** [comment]
Good question. The fact that the `base64` returns an error is normal, but it is a bit harsh for `rfc2047` to always return an error. We know how email world is not perfect in reality, I think we should introduce a new entry in the decoder next to `skip_encoded_word_length` (which is a good example btw, in theory encoded words should not be bigger than X chars but in practice it happens, it is good to propose a fallback). By default it could be `false` (it should fail on invalid base64 string), and `true` means "try to recover this base64 string and extract some lossy decoded string".

**Comment by TornaxO7** [comment]
Hm... this sounds fine. By the way, shouldn't we introduce a `decode_config` like in [base64](https://docs.rs/base64/0.13.1/base64/fn.decode_config.html) in order to give users a standard way to set those flags?

**Comment by soywod** [comment]
> Hm... this sounds fine. By the way, shouldn't we introduce a `decode_config` like in [base64](https://docs.rs/base64/0.13.1/base64/fn.decode_config.html) in order to give users a standard way to set those flags?

No need, default flags are set by our [`decode`](https://github.com/soywod/rfc2047-decoder/blob/37af83b525ac7ff7269c94e64a795545bfa32ef9/src/lib.rs#L10-L14) function. If someone wants to set flags he has to use the [`Decoder`](https://github.com/soywod/rfc2047-decoder/blob/37af83b525ac7ff7269c94e64a795545bfa32ef9/src/decoder.rs#L21) builder.

**Comment by TornaxO7** [comment]
hm... ok

**Comment by TornaxO7** [comment]
@soywod what would you recmomend to do, if the base64 encoder fails due to a not valid character? Should it just skip the whole "base64-encoded" word?

**Comment by TornaxO7** [comment]
I could use the same [strategy enum](https://github.com/TornaxO7/rfc2047-decoder/blob/fix_too_long_encoded_word/src/decoder.rs#L18-L28) for this one :)

**Comment by soywod** [comment]
Totally, it is a good idea!

**Comment by TornaxO7** [comment]
Hm... so we've got a little problem here because I can't use the [RecoveryStrategy::Decode](https://github.com/TornaxO7/rfc2047-decoder/blob/fix_too_long_encoded_word/src/decoder.rs#L30) strategy since the `base64` crate doesn't allow decoding even if the encoding contains invalid characters. Any suggestions?

**Comment by soywod** [comment]
> I can't use the RecoveryStrategy::Decode strategy since the base64
> crate doesn't allow decoding even if the encoding contains invalid
> characters. Any suggestions?

What about sanitizing or cleaning the base64 string before parsing it?

**Comment by TornaxO7** [comment]
hm... do you think, re-decoding the base-64 encoded string again and again and removing all invalid bytes until it succeeds is a fine strategy if you still want to decode the encoded word, although it's not correctly encoded according to base64?

**Comment by soywod** [comment]
> do you think, re-decoding the base-64 encoded string again and again
> and removing all invalid bytes until it succeeds is a fine strategy

Not so fan, sounds more like a hack. I don't think we should try to
guess what is the correct form of the base64.

**Comment by TornaxO7** [comment]
hm... but then I'm unsure how we can sanitize or cleanup the invalid base64-encoded string :thinking:

**Comment by soywod** [comment]
> then I'm unsure how we can sanitize or cleanup the invalid
> base64-encoded string

I guess just return an error?

---

I have less time to allocate to this project, especially for the fact
that I don't use it anymore. Would you like to be the owner and
therefore the main maintainer?

**Comment by TornaxO7** [comment]
> I have less time to allocate to this project, especially for the fact
that I don't use it anymore. Would you like to be the owner and
therefore the main maintainer?

oh eh, that's suprising me now. Don't you use it in himalaya? If you don't have time for this project, then you can mark me as the maintainer of it.

**Comment by soywod** [comment]
> Don't you use it in himalaya?

I think I don't anymore since I changed the whole email parser from
`mailparse` to `mail_parser`, and this last one seems to work better
overall, no need for external small parsers.

> If you don't have time for this project, then you can mark me as the
> maintainer of it.

Awesome, then I will push a last commit and let you know.

Thank you,

**Comment by soywod** [comment]
> Awesome, then I will push a last commit and let you know.

Could you delete your rfc2047-decoder fork so I can transfer the project
ownership?

**Comment by TornaxO7** [comment]
done.

**Comment by TornaxO7** [comment]
> I think I don't anymore since I changed the whole email parser from
`mailparse` to `mail_parser`, and this last one seems to work better
overall, no need for external small parsers.

oh, ok.

**Comment by TornaxO7** [comment]
@soywod (little reminder to transfer the maintainance)

**Comment by soywod** [comment]
> little reminder to transfer the maintainance

Request sent!

**Comment by TornaxO7** [comment]
Hm... I think that I'll close this, because I can't find a way to parse the string "lossy" if the base64 encoding is wrong.
